### ISSUE TITLE
Injected EntityManager in service class is always null for enqueuing jobs

### ISSUE THREAD

**Issue by ahofmeister** [jobrunr/example-quarkus#1]
Hi there,

it's hard to describe what's going on here, but the EntityManager in the service class `MyService` is always null. 
But it works one level above, in the resource class `JobResource`. I cloned this example and provided a reproducer with embedded H2 database: https://github.com/ahofmeister/example-quarkus

The key part is here:

```
@GET
  @Path("/add")
  @Transactional
  @Produces(MediaType.APPLICATION_JSON)
  public SimpleResponse addJob() {

    Food food = new Food();
    food.name = "apple";
    entityManager.persist(food);

    System.out.println(food.id);


    Instant date = Instant.now().truncatedTo(ChronoUnit.DAYS);
    jobScheduler.<MyService>enqueue(myService -> myService.add(date, "12"));
    return new SimpleResponse("Job Enqueued");
  }
```

Persisting the `food` works well, but not inside the `add` method of the service. 

I hope it is clear so far.

**Comment by ahofmeister** [comment]
@rdehuyss Hi. Do you mind to give me any hints?

**Comment by rdehuyss** [comment]
Question: is that in native mode?

I know H2 is not supported in native mode. 

I'm currently also not at home (holiday). Monday I'll should have some time.

**Comment by ahofmeister** [comment]
@rdehuyss Nope, it is not in native mode. But even with PostgreSQL, it wont work in the reproducer. Thanks for answering and happy holidays! :)

**Comment by rdehuyss** [comment]
Resolved in https://github.com/ahofmeister/example-quarkus/pull/1.

Reason was that you were using JobRunr v0.9.11. In v0.9.12 there was a bugfix regarding IoC injections. See https://github.com/jobrunr/jobrunr/releases/tag/v0.9.12 for more info.

**Comment by ahofmeister** [comment]
@rdehuyss Glad to hear. :) Thanks!
